language: python
python:
  - 2.7
#  - 3.4
#  - 3.6

matrix:
  include:
    - python: 3.6
      install: pip install mypy
      script: mypy --ignore-missing-imports .

cache: pip

branches:
  only:
  - master
  - /^1\..*/
 
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-build.txt
  - pip install -e .

script:
  - pytest
