language: python
python:
  - 2.7
#  - 3.4
  - 3.6

cache: pip

branches:
  only:
  - master
  - /^1\..*/
 
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-build.txt
  - pip install -e .

script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then pip install mypy ; fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then mypy --ignore-missing-imports . ; fi
  
  - pytest
 
